### ISSUE TITLE
Column header not fixed on Edge

### ISSUE THREAD

**Issue by alcbotta** [GuillaumeJasmin/react-table-hoc-fixed-columns#14]
Hi,

first of all, thank you very much for this HOC. 
I am facing a problem with edge where the column header does not stay fixed.
To make sure it wasn't a problem with my code, I tried the sample from sandbox (https://codesandbox.io/s/jnjv6j495y) and faced the same problem (the columns header "First Name" and "Last Name" as well as "Status" do not stay fixed).

Edge version: Microsoft Edge 42.17134.1.0
react-table-hoc-fixed-columns: 1.0.1

Thank you.
Cheers

**Comment by GuillaumeJasmin** [comment]
Hi,

Thanks for your feedback. I will check that soon :)

**Comment by vitorhugoanjos** [comment]
Any update on this issue?

**Comment by GuillaumeJasmin** [comment]
I tried on window 8 with IE 11, and it works.
I haven't any window 10 with Edge, so I can't try with the same environment that yours.
So feel free to make a PR if you find how to fix it.

**Comment by GuillaumeJasmin** [comment]
I think the issue come from a bad support of sticky position on Edge.
`react-table-hoc-fixed-columns` automatically detect if the browser support sticky position.
If yes, a "sticky position" version of fixed columns is used.
If not, a "scroll event" version is used, for legacy browsers.

But you can manually choose which version use. [See detail here](https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns#legacy-browsers)

[Edge support sticky position](https://caniuse.com/#search=sticky), so the sticky position version is used, but maybe the support on Edge is not complete.
Maybe you can try to force the legacy browsers version, and see if it works ?

Instead of this:
```js
import withFixedColumns from 'react-table-hoc-fixed-columns'
import ReactTable from 'react-table';

const Table = withFixedColumns(ReactTable);
```

Try this:
```js
import { withFixedColumnsScrollEvent } from 'react-table-hoc-fixed-columns'
import ReactTable from 'react-table';

const Table = withFixedColumnsScrollEvent(ReactTable);
```

**Comment by at-webdev** [comment]
@GuillaumeJasmin 
Does react-table-sticky support on IE11 & Edge browsers for fixed column? or  Is there a way to force scroll event for  these legacy browsers as in react- table-hoc-fixed-columns.

**Comment by GuillaumeJasmin** [comment]
@at-webdev please post issue related to react-table-sticky in the correct repo.

react-table-sticky use sticky position without fallback. So you can check support info here https://caniuse.com/#search=sticky
