### ISSUE TITLE
Possible to configure border styles?

### ISSUE THREAD

**Issue by irace** [GuillaumeJasmin/react-table-hoc-fixed-columns#19]
I can’t seem to figure out a way to configure the following style. It doesn't look possible from looking at the source, but perhaps I’m missing something.

```javascript
export const border = 'solid 1px #ccc !important';
```

If not, perhaps I’ll fork and add this capability. Thanks!

**Comment by GuillaumeJasmin** [comment]
Hi,
Yes, styles on v1 is not completely customisable, and that’s why I start a v2 since fews weeks, with a complete rewrite of styles. v2 is still in beta because I don’t currently use it daily, so I need feedback, but it works.

v2 don’t use css in js anymore, but only classic css file with static className, so it’s fully customisable.

So you can try v2 beta, it should fix your issue, as you can now override styles with the statics className provided.
Check the release note of v2.0.0-beta.1 and v2.0.0-beta.2, and the README.md of v2 branch.

I’m waiting your feedback on this v2 :)

**Comment by GuillaumeJasmin** [comment]
All style are now here: https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/blob/v2/src/lib/styles.css

So you have the full path of each style and can now override it in your own css style sheet

**Comment by nerdo** [comment]
I tried this, and it looks like the headers aren't sticking in this branch.

**Comment by GuillaumeJasmin** [comment]
@nerdo v2 demo is here: https://codesandbox.io/s/kowzlm5jp7
