### ISSUE TITLE
Is it possible to make scrollbar start after the sticky header/columns?

### ISSUE THREAD

**Issue by DrorSC** [GuillaumeJasmin/react-table-hoc-fixed-columns#32]
Hey! Thanks for this one, it works great!
Just trying to make some style adjustments and couldn't figure out how..
I want my scroll bars to start after the sticky header/columns. is there a way to achieve this? ty :)
[example](https://imggmi.com/full/2019/5/6/c60afed6d628aff6d1439f482e1ba776-full.png.html)

**Comment by GuillaumeJasmin** [comment]
Hi,
Thanks for your feedback.
It's no possible to start the scroll bar after the sticky header/columns.
There is many tricks in this package in order to have both sticky header and footer, and left / right sticky columns, but that tricks doesn't make possible to achieve what you want with the current version of react-table.
You should see `react-table-hoc-fixed-columns` as a works around for sticky left / right column, and there is no perfect solution until react-table rewrite (see react-table v7)
