### ISSUE TITLE
Footer Styling Incorrect

### ISSUE THREAD

**Issue by spyke01** [GuillaumeJasmin/react-table-hoc-fixed-columns#7]
It appears that when using footers the original Footer element does not have the proper styling applied.

The floating footer appears to not have any of the additional styling added, specifically the following items:

```css
position: absolute;
/*height: 100%; - Causes overflow on scrolling container*/
background-color: rgb(255, 255, 255);
z-index: 3;
left: 0px;
```

The original footer element seems to be missing the following additional style:

```css
visibility: hidden
```

**Comment by GuillaumeJasmin** [comment]
Yes, you're right ! I will test and fix it tonight

**Comment by GuillaumeJasmin** [comment]
I think I doesn't completely understand. Which version do you use ?
If you used `v0` it's an old version with some know issues, and I currently work on `v1` .
`v1.0.0-beta.8` is available.

However, since `beta-8`, I changed the way of fixed columns work, and use position sticky, in order to avoid poor animation on scroll. But I keep a fallback for browser which not support it.

But I just discovered that did break the footer. So if you use `v1 beta`, I suggest you to force fixed columns with the fallback (scroll event) instead of position sticky.

[See the fallback example here](https://github.com/GuillaumeJasmin/react-table-hoc-fixed-columns/tree/next#legacy-browsers)

**Comment by GuillaumeJasmin** [comment]
Footer bug with `beta-8` is fix on `beta-9` . See #9 

However I don't think that bug is the same as yours ?

**Comment by GuillaumeJasmin** [comment]
Yes, test with the v1 beta because it’s completely different than v0, and even if it’s a beta, it’s more advanced than v0

**Comment by GuillaumeJasmin** [comment]
@spyke01 `v1` was released few weeks ago. Did this new version fixed your issue with the footer styling ?
